clases = {
    "normal_bow":{
        "name":"normal_bow",
        "sprite":"arrow_1.png",
        "bullet":"arrow_1.png",
        "alcance":"largo",
        "dammage":3,
        "height":32,
        "width":32,
        "speed":20,
        "animated":False,
        "time_span":2,
        "active":True
    },
    "gold_bow":{
        "name":"gold_bow",
        "sprite":"arrow_2.png",
        "bullet":"arrow_2.png",
        "alcance":"largo",
        "dammage":5,
        "height":32,
        "width":32,
        "speed":4,
        "animated":False,
        "time_span":2,
        "active":True
    },
    "normal_bomerang":{
        "name":"normal_bomerang",
        "sprite":"bow_1.png",
        "bullet":"bow_1.png",
        "alcance":"largo",
        "dammage":3,
        "height":32,
        "width":32,
        "speed":10,
        "animated":True,
        "time_span":1,
        "time_span":1,
        "active":True
    },
    "normal_sword":{
        "name":"normal_sword",
        "sprite":"sword_1.png",
        "alcance":"corto",
        "dammage":5,
        "height":25,
        "width":25,
        "speed":0,
        "animated":False,
        "time_span":0.5,
        "active":True
    },
    "normal_gun":{
        "name":"normal_gun",
        "sprite":"gun_1.png",
        "bullet":"bullet_1.png",
        "alcance":"largo",
        "dammage":5,
        "height":8,
        "width":8,
        "speed":15,
        "animated":False,
        "time_span":0.5,
        "active":True
    }
}
